### ISSUE TITLE
Release fails: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by WGierke** [heroku/heroku-container-tools#172]
Hey everyone,
I tried to release a Docker image but I'm getting this stack trace:
```bash
Remote addons: bonsai (1)
Local addons:  (0)
Missing addons:  (0)
Creating local slug...
web uses an image, skipping
/home/user/.local/share/heroku/plugins/node_modules/heroku-container-tools/commands/release.js:121
        var imageId = tokens[tokens.length - 1];
                                   ^

TypeError: Cannot read property 'length' of null
    at ChildProcess.onBuildExit (/home/user/.local/share/heroku/plugins/node_modules/heroku-container-tools/commands/release.js:121:36)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
Did someone of you ran into the same error? It also happened without the bonsai addon

**Comment by dmathieu** [comment]
Willi,

This plugin is deprecated.
Could you try using our [container registry and runtime](https://devcenter.heroku.com/articles/container-registry-and-runtime) instead?

**Comment by WGierke** [comment]
Of course!
Thanks and sorry for the inconvenience
